version: "3"

services:

  facelock_django:
    build:
      context: ../
      dockerfile: production.django.Dockerfile
    env_file:
      - .env.facelock_django
    command: gunicorn facelock.wsgi:application -b 0.0.0.0:8000
    networks:
      facelock_net_production:
        ipv4_address: 172.16.77.11
    depends_on:
      - facelock_postgres

  facelock_postgres:
    image: postgres:11.3-alpine
    env_file:
      - .env.facelock_postgres
    networks:
      facelock_net_production:
        ipv4_address: 172.16.77.12

  facelock_nginx:
    build:
      context: ../
      dockerfile: production.nginx.Dockerfile
    networks:
      facelock_net_production:
        ipv4_address: 172.16.77.10
    ports:
      - 80:80
    depends_on:
      - facelock_django        

networks:
  facelock_net_production:
    ipam:
      driver: default
      config:
        - subnet: 172.16.77.0/24
