version: "3"

services:

  facelock_django:
    build:
      context: ../facelock/ 
      dockerfile: development.Dockerfile
    volumes:
      - ../facelock/:/facelock/
    env_file:
      - .env.facelock_django
    command: gunicorn facelock.wsgi:application -b 0.0.0.0:8000
    networks:
      facelock_net_development:
        ipv4_address: 172.16.50.11
    depends_on:
      - facelock_postgres

  facelock_postgres:
    image: postgres:11.3-alpine
    env_file:
      - .env.facelock_postgres
    networks:
      facelock_net_development:
        ipv4_address: 172.16.50.12

  facelock_nginx:
    build:
      context: ../nginx/
      dockerfile: development.Dockerfile
    volumes:
      - ../nginx/conf.d/:/etc/nginx/conf.d/
      - ../staticfiles/production/:/staticfiles/production/
      - ../staticfiles/img/:/staticfiles/img/
    networks:
      facelock_net_development:
        ipv4_address: 172.16.50.10


volumes:
  postgres_database:

networks:
  facelock_net_development:
    ipam:
      driver: default
      config:
        - subnet: 172.16.50.0/24
